### ISSUE TITLE
Feature request: support multiple yarn.lock files

### ISSUE THREAD

**Issue by elektronik2k5** [Simek/yarn-lock-changes#29]
Hello and thanks for developing and maintaining this action!

I have a bit of an unusual setup, in which my repo contains several projects. Sort of like a monorepo, but without all the extra tooling. Basically, my repo is in transition from a legacy app to a modern one:

`/package.json` and `/yarn.lock` for shared devDependencies.
`/legacy-app/package.json` and `/legacy-app/yarn.lock` for the legacy app.
`/modern-app/package.json` and `/modern-app/yarn.lock` for the modern app.

Is there a chance to add support for either detecting multiple `yarn.lock` files - or - specifying them explicitly, just like the current `path` allows, but for more than one?

**Comment by Simek** [comment]
Hi @elektronik2k5, thank you for the kind words. 🙂 

At this moment, to perform check on many locks you can just use the action multiple times:
```yml
name: Yarn Lock Changes
on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Yarn Lock Changes Main
        uses: Simek/yarn-lock-changes@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Yarn Lock Changes Legacy App
        uses: Simek/yarn-lock-changes@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: 'legacy-app/yarn.lock'
```
You can also use the [`dorny/paths-filter`](https://github.com/dorny/paths-filter) action to run the lock checks conditionally.

Alternatively, you can create separate workflow files for each of the apps, but it might be an overkill, if you do not have the separate workflows for each app already implemented in.

Please let me know, if at least one of the suggestions is feasible in your case. If not I will look at possibility to support array inputs in `path`.
