### ISSUE TITLE
Permissions not sufficient within private repositories

### ISSUE THREAD

**Issue by chrispader** [Simek/yarn-lock-changes#57]
# Problem

Using the example in the `README.md` within private repositories causes the `checkout` job to crash with the following error:
```shell
remote: Repository not found.
Error: fatal: repository 'https://github.com/<your_user>/<your_repo>/' not found
```

This problem is already tracked [here](https://github.com/actions/checkout/issues/254).

# Solution
 
In order to use this action within private repositories, i also needed to add write permissions for `id-token` and read permissions for `contents` to the job, as described [here](https://github.com/actions/checkout/issues/254#issuecomment-981945812), so it looks like something like this:

```yaml
...

yarn_lock_changes:
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write
        id-token: write
        contents: read

...
```
